import type { CodeAnalyzeResponse, CodeExample } from "./types.js";

export const fibonacciCode = `def fib(n):
    if n <= 1:
        return n
    return fib(n - 1) + fib(n - 2)

print(fib(4))`;

const binarySearchCode = `def binary_search(nums, target):
    left, right = 0, len(nums) - 1
    while left <= right:
        mid = (left + right) // 2
        if nums[mid] == target:
            return mid
        elif nums[mid] < target:
            left = mid + 1
        else:
            right = mid - 1
    return -1

print(binary_search([1, 3, 5, 7, 9], 7))`;

export const examples: CodeExample[] = [
  {
    id: "fibonacci-recursion",
    title: "斐波那契递归",
    category: "recursion",
    difficulty: "beginner",
    concepts: ["recursion", "base-case"],
    code: fibonacciCode,
    expectedVisualization: [
      "timeline",
      "stack",
      "recursion-tree",
      "variables",
    ],
  },
  {
    id: "binary-search",
    title: "二分查找",
    category: "binary-search",
    difficulty: "beginner",
    concepts: ["binary-search", "boundary"],
    code: binarySearchCode,
    expectedVisualization: ["timeline", "stack", "variables"],
  },
  {
    id: "bracket-stack",
    title: "括号匹配",
    category: "stack",
    difficulty: "beginner",
    concepts: ["stack", "matching"],
    code: `def is_valid(s):
    stack = []
    pairs = {')': '(', ']': '[', '}': '{'}
    for ch in s:
        if ch in '([{':
            stack.append(ch)
        elif ch in pairs:
            if not stack or stack[-1] != pairs[ch]:
                return False
            stack.pop()
    return not stack

print(is_valid('([])'))`,
    expectedVisualization: ["timeline", "stack", "variables"],
  },
  {
    id: "depth-first-search",
    title: "深度优先搜索",
    category: "dfs",
    difficulty: "beginner",
    concepts: ["traversal", "visited"],
    code: `def dfs(grid, row, col, visited):
    if row < 0 or row >= len(grid) or col < 0 or col >= len(grid[0]):
        return
    if grid[row][col] == 0 or (row, col) in visited:
        return
    visited.add((row, col))
    for dr, dc in [(1, 0), (-1, 0), (0, 1), (0, -1)]:
        dfs(grid, row + dr, col + dc, visited)

grid = [
    [1, 1, 0],
    [0, 1, 1],
    [0, 0, 1],
]
visited = set()
dfs(grid, 0, 0, visited)
print(len(visited))`,
    expectedVisualization: ["timeline", "stack", "variables"],
  },
  {
    id: "climbing-stairs",
    title: "爬楼梯",
    category: "dp",
    difficulty: "intermediate",
    concepts: ["dp", "state-transition"],
    code: `def climb(n):
    previous, current = 1, 1
    for _ in range(n):
        previous, current = current, previous + current
    return previous

print(climb(5))`,
    expectedVisualization: ["timeline", "variables"],
  },
];

export const fibonacciAnalysis: CodeAnalyzeResponse = {
  requestId: "mock-fibonacci-base",
  language: "python",
  title: "斐波那契递归执行过程",
  summary:
    "fib(4) 会拆分成更小的 fib 调用，直到 fib(1) 或 fib(0) 命中递归出口，再逐层合并返回值。",
  detectedConcepts: ["递归", "base case", "调用栈", "分治"],
  complexity: {
    time: "O(2^n)",
    space: "O(n)",
    explanation:
      "朴素递归会重复计算相同子问题；最大递归深度与 n 成正比。",
  },
  lineExplanations: [
    {
      line: 1,
      code: "def fib(n):",
      explanation: "定义接收整数 n 的斐波那契函数。",
      role: "input",
    },
    {
      line: 2,
      code: "if n <= 1:",
      explanation: "判断是否到达 fib(0) 或 fib(1) 的递归出口。",
      role: "condition",
    },
    {
      line: 3,
      code: "return n",
      explanation: "出口直接返回 0 或 1，停止继续向下递归。",
      role: "return",
    },
    {
      line: 4,
      code: "return fib(n - 1) + fib(n - 2)",
      explanation: "分别计算两个更小的子问题，并将返回值相加。",
      role: "recursive-call",
    },
    {
      line: 6,
      code: "print(fib(4))",
      explanation: "从 fib(4) 开始执行，并输出最终结果 3。",
      role: "output",
    },
  ],
  traceSteps: [
    {
      step: 1,
      line: 6,
      event: "start",
      description: "程序准备计算 fib(4)。",
      variables: { n: 4 },
      changedVariables: ["n"],
    },
    {
      step: 2,
      line: 1,
      event: "call",
      description: "进入 fib(4)，创建根调用帧。",
      variables: { n: 4 },
      changedVariables: ["n"],
      activeFrameId: "frame-f4",
      activeRecursionNodeId: "fib-4",
    },
    {
      step: 3,
      line: 2,
      event: "condition",
      description: "4 <= 1 为 False，需要继续递归。",
      variables: { n: 4, isBaseCase: false },
      changedVariables: ["isBaseCase"],
      activeFrameId: "frame-f4",
      activeRecursionNodeId: "fib-4",
    },
    {
      step: 4,
      line: 4,
      event: "call",
      description: "fib(4) 首先调用 fib(3)。",
      variables: { n: 3 },
      changedVariables: ["n"],
      activeFrameId: "frame-f3",
      activeRecursionNodeId: "fib-3",
    },
    {
      step: 5,
      line: 4,
      event: "call",
      description: "fib(3) 首先调用 fib(2)。",
      variables: { n: 2 },
      changedVariables: ["n"],
      activeFrameId: "frame-f2-left",
      activeRecursionNodeId: "fib-2-left",
    },
    {
      step: 6,
      line: 4,
      event: "call",
      description: "fib(2) 调用 fib(1)。",
      variables: { n: 1 },
      changedVariables: ["n"],
      activeFrameId: "frame-f1-left",
      activeRecursionNodeId: "fib-1-left",
    },
    {
      step: 7,
      line: 3,
      event: "return",
      description: "fib(1) 命中 base case，返回 1。",
      variables: { n: 1, returnValue: 1 },
      changedVariables: ["returnValue"],
      activeFrameId: "frame-f1-left",
      activeRecursionNodeId: "fib-1-left",
    },
    {
      step: 8,
      line: 4,
      event: "call",
      description: "fib(2) 继续调用 fib(0)。",
      variables: { n: 0 },
      changedVariables: ["n"],
      activeFrameId: "frame-f0-left",
      activeRecursionNodeId: "fib-0-left",
    },
    {
      step: 9,
      line: 3,
      event: "return",
      description: "fib(0) 命中 base case，返回 0。",
      variables: { n: 0, returnValue: 0 },
      changedVariables: ["returnValue"],
      activeFrameId: "frame-f0-left",
      activeRecursionNodeId: "fib-0-left",
    },
    {
      step: 10,
      line: 4,
      event: "return",
      description: "fib(2) 合并 1 + 0，返回 1。",
      variables: { n: 2, leftValue: 1, rightValue: 0, returnValue: 1 },
      changedVariables: ["returnValue"],
      activeFrameId: "frame-f2-left",
      activeRecursionNodeId: "fib-2-left",
    },
    {
      step: 11,
      line: 4,
      event: "call",
      description: "fib(3) 再调用 fib(1)。",
      variables: { n: 1 },
      changedVariables: ["n"],
      activeFrameId: "frame-f1-middle",
      activeRecursionNodeId: "fib-1-middle",
    },
    {
      step: 12,
      line: 3,
      event: "return",
      description: "第二个 fib(1) 返回 1。",
      variables: { n: 1, returnValue: 1 },
      changedVariables: ["returnValue"],
      activeFrameId: "frame-f1-middle",
      activeRecursionNodeId: "fib-1-middle",
    },
    {
      step: 13,
      line: 4,
      event: "return",
      description: "fib(3) 合并 1 + 1，返回 2。",
      variables: { n: 3, leftValue: 1, rightValue: 1, returnValue: 2 },
      changedVariables: ["returnValue"],
      activeFrameId: "frame-f3",
      activeRecursionNodeId: "fib-3",
    },
    {
      step: 14,
      line: 4,
      event: "call",
      description: "fib(4) 开始计算右侧的 fib(2)。",
      variables: { n: 2 },
      changedVariables: ["n"],
      activeFrameId: "frame-f2-right",
      activeRecursionNodeId: "fib-2-right",
    },
    {
      step: 15,
      line: 4,
      event: "call",
      description: "右侧 fib(2) 调用 fib(1)。",
      variables: { n: 1 },
      changedVariables: ["n"],
      activeFrameId: "frame-f1-right",
      activeRecursionNodeId: "fib-1-right",
    },
    {
      step: 16,
      line: 3,
      event: "return",
      description: "右侧 fib(1) 返回 1。",
      variables: { n: 1, returnValue: 1 },
      changedVariables: ["returnValue"],
      activeFrameId: "frame-f1-right",
      activeRecursionNodeId: "fib-1-right",
    },
    {
      step: 17,
      line: 4,
      event: "call",
      description: "右侧 fib(2) 调用 fib(0)。",
      variables: { n: 0 },
      changedVariables: ["n"],
      activeFrameId: "frame-f0-right",
      activeRecursionNodeId: "fib-0-right",
    },
    {
      step: 18,
      line: 3,
      event: "return",
      description: "右侧 fib(0) 返回 0。",
      variables: { n: 0, returnValue: 0 },
      changedVariables: ["returnValue"],
      activeFrameId: "frame-f0-right",
      activeRecursionNodeId: "fib-0-right",
    },
    {
      step: 19,
      line: 4,
      event: "return",
      description: "右侧 fib(2) 合并 1 + 0，返回 1。",
      variables: { n: 2, leftValue: 1, rightValue: 0, returnValue: 1 },
      changedVariables: ["returnValue"],
      activeFrameId: "frame-f2-right",
      activeRecursionNodeId: "fib-2-right",
    },
    {
      step: 20,
      line: 4,
      event: "return",
      description: "fib(4) 合并 2 + 1，返回 3。",
      variables: { n: 4, leftValue: 2, rightValue: 1, returnValue: 3 },
      changedVariables: ["returnValue"],
      activeFrameId: "frame-f4",
      activeRecursionNodeId: "fib-4",
    },
    {
      step: 21,
      line: 6,
      event: "output",
      description: "print 输出 fib(4) 的结果 3。",
      variables: { result: 3 },
      changedVariables: ["result"],
      stdout: "3",
    },
    {
      step: 22,
      line: 6,
      event: "end",
      description: "程序执行结束。",
      variables: { result: 3 },
      changedVariables: [],
      stdout: "3",
    },
  ],
  stackFrames: [
    {
      step: 2,
      frames: [
        {
          id: "frame-f4",
          functionName: "fib",
          line: 1,
          params: { n: 4 },
          locals: {},
          status: "active",
        },
      ],
    },
    {
      step: 5,
      frames: [
        {
          id: "frame-f4",
          functionName: "fib",
          line: 4,
          params: { n: 4 },
          locals: {},
          status: "waiting",
        },
        {
          id: "frame-f3",
          functionName: "fib",
          line: 4,
          params: { n: 3 },
          locals: {},
          status: "waiting",
        },
        {
          id: "frame-f2-left",
          functionName: "fib",
          line: 1,
          params: { n: 2 },
          locals: {},
          status: "active",
        },
      ],
    },
    {
      step: 7,
      frames: [
        {
          id: "frame-f4",
          functionName: "fib",
          line: 4,
          params: { n: 4 },
          locals: {},
          status: "waiting",
        },
        {
          id: "frame-f3",
          functionName: "fib",
          line: 4,
          params: { n: 3 },
          locals: {},
          status: "waiting",
        },
        {
          id: "frame-f2-left",
          functionName: "fib",
          line: 4,
          params: { n: 2 },
          locals: { leftValue: 1 },
          status: "active",
        },
        {
          id: "frame-f1-left",
          functionName: "fib",
          line: 3,
          params: { n: 1 },
          locals: {},
          status: "returned",
          returnValue: 1,
        },
      ],
    },
    {
      step: 9,
      frames: [
        {
          id: "frame-f4",
          functionName: "fib",
          line: 4,
          params: { n: 4 },
          locals: {},
          status: "waiting",
        },
        {
          id: "frame-f3",
          functionName: "fib",
          line: 4,
          params: { n: 3 },
          locals: {},
          status: "waiting",
        },
        {
          id: "frame-f2-left",
          functionName: "fib",
          line: 4,
          params: { n: 2 },
          locals: { leftValue: 1, rightValue: 0 },
          status: "active",
        },
        {
          id: "frame-f0-left",
          functionName: "fib",
          line: 3,
          params: { n: 0 },
          locals: {},
          status: "returned",
          returnValue: 0,
        },
      ],
    },
    {
      step: 12,
      frames: [
        {
          id: "frame-f4",
          functionName: "fib",
          line: 4,
          params: { n: 4 },
          locals: {},
          status: "waiting",
        },
        {
          id: "frame-f3",
          functionName: "fib",
          line: 4,
          params: { n: 3 },
          locals: { leftValue: 1, rightValue: 1 },
          status: "active",
        },
        {
          id: "frame-f1-middle",
          functionName: "fib",
          line: 3,
          params: { n: 1 },
          locals: {},
          status: "returned",
          returnValue: 1,
        },
      ],
    },
    {
      step: 13,
      frames: [
        {
          id: "frame-f4",
          functionName: "fib",
          line: 4,
          params: { n: 4 },
          locals: { leftValue: 2 },
          status: "active",
        },
        {
          id: "frame-f3",
          functionName: "fib",
          line: 4,
          params: { n: 3 },
          locals: { leftValue: 1, rightValue: 1 },
          status: "returned",
          returnValue: 2,
        },
      ],
    },
    {
      step: 14,
      frames: [
        {
          id: "frame-f4",
          functionName: "fib",
          line: 4,
          params: { n: 4 },
          locals: { leftValue: 2 },
          status: "waiting",
        },
        {
          id: "frame-f2-right",
          functionName: "fib",
          line: 1,
          params: { n: 2 },
          locals: {},
          status: "active",
        },
      ],
    },
    {
      step: 16,
      frames: [
        {
          id: "frame-f4",
          functionName: "fib",
          line: 4,
          params: { n: 4 },
          locals: { leftValue: 2 },
          status: "waiting",
        },
        {
          id: "frame-f2-right",
          functionName: "fib",
          line: 4,
          params: { n: 2 },
          locals: { leftValue: 1 },
          status: "active",
        },
        {
          id: "frame-f1-right",
          functionName: "fib",
          line: 3,
          params: { n: 1 },
          locals: {},
          status: "returned",
          returnValue: 1,
        },
      ],
    },
    {
      step: 18,
      frames: [
        {
          id: "frame-f4",
          functionName: "fib",
          line: 4,
          params: { n: 4 },
          locals: { leftValue: 2 },
          status: "waiting",
        },
        {
          id: "frame-f2-right",
          functionName: "fib",
          line: 4,
          params: { n: 2 },
          locals: { leftValue: 1, rightValue: 0 },
          status: "active",
        },
        {
          id: "frame-f0-right",
          functionName: "fib",
          line: 3,
          params: { n: 0 },
          locals: {},
          status: "returned",
          returnValue: 0,
        },
      ],
    },
    {
      step: 20,
      frames: [
        {
          id: "frame-f4",
          functionName: "fib",
          line: 4,
          params: { n: 4 },
          locals: { leftValue: 2, rightValue: 1 },
          status: "returned",
          returnValue: 3,
        },
      ],
    },
  ],
  recursionTree: {
    rootId: "fib-4",
    nodes: [
      {
        id: "fib-4",
        label: "fib(4)",
        functionName: "fib",
        args: { n: 4 },
        status: "returned",
        returnValue: 3,
        enterStep: 2,
        exitStep: 20,
      },
      {
        id: "fib-3",
        label: "fib(3)",
        functionName: "fib",
        args: { n: 3 },
        status: "returned",
        returnValue: 2,
        enterStep: 4,
        exitStep: 13,
      },
      {
        id: "fib-2-left",
        label: "fib(2)",
        functionName: "fib",
        args: { n: 2 },
        status: "returned",
        returnValue: 1,
        enterStep: 5,
        exitStep: 10,
      },
      {
        id: "fib-1-left",
        label: "fib(1)",
        functionName: "fib",
        args: { n: 1 },
        status: "returned",
        returnValue: 1,
        enterStep: 6,
        exitStep: 7,
      },
      {
        id: "fib-0-left",
        label: "fib(0)",
        functionName: "fib",
        args: { n: 0 },
        status: "returned",
        returnValue: 0,
        enterStep: 8,
        exitStep: 9,
      },
      {
        id: "fib-1-middle",
        label: "fib(1)",
        functionName: "fib",
        args: { n: 1 },
        status: "returned",
        returnValue: 1,
        enterStep: 11,
        exitStep: 12,
      },
      {
        id: "fib-2-right",
        label: "fib(2)",
        functionName: "fib",
        args: { n: 2 },
        status: "returned",
        returnValue: 1,
        enterStep: 14,
        exitStep: 19,
      },
      {
        id: "fib-1-right",
        label: "fib(1)",
        functionName: "fib",
        args: { n: 1 },
        status: "returned",
        returnValue: 1,
        enterStep: 15,
        exitStep: 16,
      },
      {
        id: "fib-0-right",
        label: "fib(0)",
        functionName: "fib",
        args: { n: 0 },
        status: "returned",
        returnValue: 0,
        enterStep: 17,
        exitStep: 18,
      },
    ],
    edges: [
      { from: "fib-4", to: "fib-3", label: "n - 1" },
      { from: "fib-4", to: "fib-2-right", label: "n - 2" },
      { from: "fib-3", to: "fib-2-left", label: "n - 1" },
      { from: "fib-3", to: "fib-1-middle", label: "n - 2" },
      { from: "fib-2-left", to: "fib-1-left", label: "n - 1" },
      { from: "fib-2-left", to: "fib-0-left", label: "n - 2" },
      { from: "fib-2-right", to: "fib-1-right", label: "n - 1" },
      { from: "fib-2-right", to: "fib-0-right", label: "n - 2" },
    ],
  },
  recommendations: [
    {
      id: "memoized-fibonacci",
      title: "给斐波那契递归添加缓存",
      difficulty: "beginner",
      concepts: ["递归", "记忆化"],
      reason: "观察并消除 fib(2) 等子问题的重复计算。",
      visualizationHint: "对比加入缓存前后的递归树节点数量。",
      starterPrompt: "使用字典保存已经计算过的 fib(n)。",
    },
    {
      id: "factorial-recursion",
      title: "跟踪阶乘递归",
      difficulty: "beginner",
      concepts: ["递归出口", "调用栈"],
      reason: "用单分支递归巩固进入与回退过程。",
      visualizationHint: "逐步查看每一层参数和返回值。",
    },
    {
      id: "iterative-fibonacci",
      title: "改写为循环版本",
      difficulty: "intermediate",
      concepts: ["循环", "状态更新", "空间优化"],
      reason: "理解相同问题如何用常量额外空间求解。",
      visualizationHint: "跟踪 previous 和 current 的每次变化。",
    },
  ],
  warnings: [],
  source: "mock",
};

export const binarySearchAnalysis: CodeAnalyzeResponse = {
  requestId: "mock-binary-search-base",
  language: "python",
  title: "二分查找区间变化",
  summary:
    "算法通过比较中点元素与目标值，不断收缩 left 和 right，最终在索引 3 找到目标 7。",
  detectedConcepts: ["二分查找", "循环", "区间边界", "整数除法"],
  complexity: {
    time: "O(log n)",
    space: "O(1)",
    explanation: "每次比较都会排除约一半搜索区间，并且只使用固定数量变量。",
  },
  lineExplanations: [
    {
      line: 1,
      code: "def binary_search(items, target):",
      explanation: "定义在有序序列中查找 target 的函数。",
      role: "input",
    },
    {
      line: 2,
      code: "left, right = 0, len(items) - 1",
      explanation: "将搜索区间初始化为整个序列。",
      role: "state-update",
    },
    {
      line: 3,
      code: "while left <= right:",
      explanation: "只要区间仍然有效，就继续查找。",
      role: "loop",
    },
    {
      line: 4,
      code: "mid = (left + right) // 2",
      explanation: "计算当前区间的中点索引。",
      role: "state-update",
    },
    {
      line: 5,
      code: "if items[mid] == target:",
      explanation: "检查中点元素是否就是目标值。",
      role: "condition",
    },
    {
      line: 6,
      code: "return mid",
      explanation: "找到目标后返回中点索引。",
      role: "return",
    },
    {
      line: 7,
      code: "if items[mid] < target:",
      explanation: "目标更大时，排除中点及其左侧区间。",
      role: "condition",
    },
    {
      line: 8,
      code: "left = mid + 1",
      explanation: "把左边界移动到中点右侧。",
      role: "state-update",
    },
    {
      line: 9,
      code: "else:",
      explanation: "否则目标位于中点左侧。",
      role: "condition",
    },
    {
      line: 10,
      code: "right = mid - 1",
      explanation: "把右边界移动到中点左侧。",
      role: "state-update",
    },
    {
      line: 11,
      code: "return -1",
      explanation: "区间耗尽仍未找到时返回 -1。",
      role: "return",
    },
    {
      line: 13,
      code: "print(binary_search([1, 3, 5, 7, 9, 11], 7))",
      explanation: "查找目标 7，并输出索引 3。",
      role: "output",
    },
  ],
  traceSteps: [
    {
      step: 1,
      line: 1,
      event: "start",
      description: "开始在 6 个有序元素中查找 7。",
      variables: { target: 7, itemCount: 6 },
      changedVariables: ["target", "itemCount"],
      activeFrameId: "frame-binary-search",
    },
    {
      step: 2,
      line: 2,
      event: "assign",
      description: "初始化搜索边界 left=0、right=5。",
      variables: { left: 0, right: 5, target: 7 },
      changedVariables: ["left", "right"],
      activeFrameId: "frame-binary-search",
    },
    {
      step: 3,
      line: 3,
      event: "loop",
      description: "0 <= 5，搜索区间有效。",
      variables: { left: 0, right: 5 },
      changedVariables: [],
      activeFrameId: "frame-binary-search",
    },
    {
      step: 4,
      line: 4,
      event: "assign",
      description: "计算中点 mid=2，中点元素为 5。",
      variables: { left: 0, right: 5, mid: 2, midValue: 5 },
      changedVariables: ["mid", "midValue"],
      activeFrameId: "frame-binary-search",
    },
    {
      step: 5,
      line: 5,
      event: "condition",
      description: "中点元素 5 不等于目标 7。",
      variables: { left: 0, right: 5, mid: 2, isMatch: false },
      changedVariables: ["isMatch"],
      activeFrameId: "frame-binary-search",
    },
    {
      step: 6,
      line: 7,
      event: "condition",
      description: "5 < 7，目标位于右半区间。",
      variables: { left: 0, right: 5, mid: 2, searchRight: true },
      changedVariables: ["searchRight"],
      activeFrameId: "frame-binary-search",
    },
    {
      step: 7,
      line: 8,
      event: "assign",
      description: "将 left 更新为 3。",
      variables: { left: 3, right: 5, mid: 2 },
      changedVariables: ["left"],
      activeFrameId: "frame-binary-search",
    },
    {
      step: 8,
      line: 3,
      event: "loop",
      description: "3 <= 5，继续搜索。",
      variables: { left: 3, right: 5, mid: 2 },
      changedVariables: [],
      activeFrameId: "frame-binary-search",
    },
    {
      step: 9,
      line: 4,
      event: "assign",
      description: "重新计算 mid=4，中点元素为 9。",
      variables: { left: 3, right: 5, mid: 4, midValue: 9 },
      changedVariables: ["mid", "midValue"],
      activeFrameId: "frame-binary-search",
    },
    {
      step: 10,
      line: 5,
      event: "condition",
      description: "中点元素 9 不等于目标值。",
      variables: { left: 3, right: 5, mid: 4, isMatch: false },
      changedVariables: ["isMatch"],
      activeFrameId: "frame-binary-search",
    },
    {
      step: 11,
      line: 7,
      event: "condition",
      description: "9 < 7 为 False，目标位于左半区间。",
      variables: { left: 3, right: 5, mid: 4, searchRight: false },
      changedVariables: ["searchRight"],
      activeFrameId: "frame-binary-search",
    },
    {
      step: 12,
      line: 10,
      event: "assign",
      description: "将 right 更新为 3。",
      variables: { left: 3, right: 3, mid: 4 },
      changedVariables: ["right"],
      activeFrameId: "frame-binary-search",
    },
    {
      step: 13,
      line: 3,
      event: "loop",
      description: "3 <= 3，继续搜索。",
      variables: { left: 3, right: 3, mid: 4 },
      changedVariables: [],
      activeFrameId: "frame-binary-search",
    },
    {
      step: 14,
      line: 4,
      event: "assign",
      description: "重新计算 mid=3，中点元素为 7。",
      variables: { left: 3, right: 3, mid: 3, midValue: 7 },
      changedVariables: ["mid", "midValue"],
      activeFrameId: "frame-binary-search",
    },
    {
      step: 15,
      line: 5,
      event: "condition",
      description: "中点元素 7 等于目标值。",
      variables: { left: 3, right: 3, mid: 3, isMatch: true },
      changedVariables: ["isMatch"],
      activeFrameId: "frame-binary-search",
    },
    {
      step: 16,
      line: 6,
      event: "return",
      description: "返回找到的索引 3。",
      variables: { left: 3, right: 3, mid: 3, returnValue: 3 },
      changedVariables: ["returnValue"],
      activeFrameId: "frame-binary-search",
    },
    {
      step: 17,
      line: 13,
      event: "output",
      description: "print 输出索引 3。",
      variables: { result: 3 },
      changedVariables: ["result"],
      stdout: "3",
    },
    {
      step: 18,
      line: 13,
      event: "end",
      description: "程序执行结束，标准输出为 3。",
      variables: { result: 3 },
      changedVariables: [],
      stdout: "3",
    },
  ],
  stackFrames: [
    {
      step: 1,
      frames: [
        {
          id: "frame-binary-search",
          functionName: "binary_search",
          line: 1,
          params: { target: 7, itemCount: 6 },
          locals: {},
          status: "active",
        },
      ],
    },
    {
      step: 4,
      frames: [
        {
          id: "frame-binary-search",
          functionName: "binary_search",
          line: 4,
          params: { target: 7, itemCount: 6 },
          locals: { left: 0, right: 5, mid: 2, midValue: 5 },
          status: "active",
        },
      ],
    },
    {
      step: 7,
      frames: [
        {
          id: "frame-binary-search",
          functionName: "binary_search",
          line: 8,
          params: { target: 7, itemCount: 6 },
          locals: { left: 3, right: 5, mid: 2 },
          status: "active",
        },
      ],
    },
    {
      step: 16,
      frames: [
        {
          id: "frame-binary-search",
          functionName: "binary_search",
          line: 6,
          params: { target: 7, itemCount: 6 },
          locals: { left: 3, right: 3, mid: 3, midValue: 7 },
          status: "returned",
          returnValue: 3,
        },
      ],
    },
  ],
  recommendations: [
    {
      id: "binary-search-missing-target",
      title: "查找不存在的目标值",
      difficulty: "beginner",
      concepts: ["边界", "循环终止"],
      reason: "练习观察 left 超过 right 时算法如何结束。",
      visualizationHint: "跟踪每轮 left、right 和 mid。",
    },
    {
      id: "binary-search-first-position",
      title: "查找重复值的第一个位置",
      difficulty: "intermediate",
      concepts: ["二分查找", "边界收缩"],
      reason: "理解找到目标后继续向左收缩的变体。",
      visualizationHint: "标记候选答案和右边界的变化。",
    },
    {
      id: "guess-number",
      title: "猜数字区间策略",
      difficulty: "beginner",
      concepts: ["二分思想", "条件分支"],
      reason: "把二分查找迁移到直观的区间问题。",
      visualizationHint: "每轮高亮保留和排除的区间。",
    },
  ],
  warnings: [],
  source: "mock",
};

export const bracketStackAnalysis: CodeAnalyzeResponse = {
  requestId: "mock-bracket-stack-base",
  language: "python",
  title: "括号匹配的栈变化",
  summary:
    "is_valid('([])') 使用栈保存左括号，遇到右括号时弹出并核对类型；两组括号都匹配且栈最终为空，因此返回 True。",
  detectedConcepts: ["栈", "括号匹配", "遍历", "提前返回"],
  complexity: {
    time: "O(n)",
    space: "O(n)",
    explanation:
      "每个字符最多入栈和出栈一次；全部为左括号时，栈最多保存 n 个字符。",
  },
  lineExplanations: [
    {
      line: 1,
      code: "def is_valid(text):",
      explanation: "定义检查括号文本是否匹配的函数。",
      role: "input",
    },
    {
      line: 2,
      code: "    stack = []",
      explanation: "创建栈来保存尚未匹配的左括号。",
      role: "state-update",
    },
    {
      line: 3,
      code: "    pairs = {')': '(', ']': '[', '}': '{'}",
      explanation: "记录每种右括号对应的左括号。",
      role: "state-update",
    },
    {
      line: 4,
      code: "    for char in text:",
      explanation: "按顺序检查输入中的每个括号。",
      role: "loop",
    },
    {
      line: 5,
      code: "        if char in '([{':",
      explanation: "判断当前字符是否为左括号。",
      role: "condition",
    },
    {
      line: 6,
      code: "            stack.append(char)",
      explanation: "把左括号压入栈，等待后续右括号匹配。",
      role: "state-update",
    },
    {
      line: 7,
      code: "        elif not stack or stack.pop() != pairs[char]:",
      explanation: "右括号到来时弹出栈顶，并检查类型是否一致。",
      role: "condition",
    },
    {
      line: 8,
      code: "            return False",
      explanation: "栈为空或括号类型不一致时立即返回 False。",
      role: "return",
    },
    {
      line: 9,
      code: "    return not stack",
      explanation: "遍历结束后，只有空栈表示全部括号都已匹配。",
      role: "return",
    },
    {
      line: 11,
      code: "print(is_valid('([])'))",
      explanation: "检查示例字符串并打印布尔结果。",
      role: "output",
    },
  ],
  traceSteps: [
    {
      step: 1,
      line: 11,
      event: "start",
      description: "开始检查文本 '([])'。",
      variables: { text: "([])", stack: "" },
      changedVariables: ["text", "stack"],
    },
    {
      step: 2,
      line: 6,
      event: "push",
      description: "读取 '(' 并压入栈。",
      variables: { char: "(", stack: "(" },
      changedVariables: ["char", "stack"],
    },
    {
      step: 3,
      line: 6,
      event: "push",
      description: "读取 '[' 并压入栈。",
      variables: { char: "[", stack: "([" },
      changedVariables: ["char", "stack"],
    },
    {
      step: 4,
      line: 7,
      event: "pop",
      description: "读取 ']'，弹出 '['，二者匹配。",
      variables: { char: "]", popped: "[", stack: "(", matched: true },
      changedVariables: ["char", "popped", "stack", "matched"],
    },
    {
      step: 5,
      line: 7,
      event: "pop",
      description: "读取 ')'，弹出 '('，二者匹配。",
      variables: { char: ")", popped: "(", stack: "", matched: true },
      changedVariables: ["char", "popped", "stack"],
    },
    {
      step: 6,
      line: 9,
      event: "return",
      description: "遍历结束且栈为空，返回 True。",
      variables: { stack: "", returnValue: true },
      changedVariables: ["returnValue"],
    },
  ],
  stackFrames: [
    {
      step: 1,
      frames: [
        {
          id: "frame-is-valid",
          functionName: "is_valid",
          line: 1,
          params: { text: "([])" },
          locals: { stack: "" },
          status: "active",
        },
      ],
    },
    {
      step: 6,
      frames: [
        {
          id: "frame-is-valid",
          functionName: "is_valid",
          line: 9,
          params: { text: "([])" },
          locals: { stack: "" },
          status: "returned",
          returnValue: true,
        },
      ],
    },
  ],
  recommendations: [],
  warnings: [],
  source: "mock",
};

export const depthFirstSearchAnalysis: CodeAnalyzeResponse = {
  requestId: "mock-depth-first-search-base",
  language: "python",
  title: "网格深度优先搜索访问过程",
  summary:
    "DFS 从 grid 的 (0, 0) 出发，只递归访问值为 1 且未访问的上下左右单元格；visited 最终包含 5 个连通单元格。",
  detectedConcepts: ["深度优先搜索", "递归", "visited 集合", "网格遍历"],
  complexity: {
    time: "O(rows * cols)",
    space: "O(rows * cols)",
    explanation:
      "每个网格位置最多被有效访问一次；visited 与最深递归路径最多覆盖全部单元格。",
  },
  lineExplanations: [
    {
      line: 1,
      code: "def dfs(grid, row, col, visited):",
      explanation: "定义从指定行列开始遍历网格的递归函数。",
      role: "input",
    },
    {
      line: 2,
      code:
        "    if row < 0 or row >= len(grid) or col < 0 or col >= len(grid[0]):",
      explanation: "越过网格边界时停止当前递归分支。",
      role: "condition",
    },
    {
      line: 4,
      code: "    if grid[row][col] == 0 or (row, col) in visited:",
      explanation: "跳过值为 0 或已经访问的单元格。",
      role: "condition",
    },
    {
      line: 6,
      code: "    visited.add((row, col))",
      explanation: "把当前可访问单元格加入 visited。",
      role: "state-update",
    },
    {
      line: 7,
      code: "    for dr, dc in [(1, 0), (-1, 0), (0, 1), (0, -1)]:",
      explanation: "枚举下、上、右、左四个相邻方向。",
      role: "loop",
    },
    {
      line: 8,
      code: "        dfs(grid, row + dr, col + dc, visited)",
      explanation: "递归访问当前单元格的相邻位置。",
      role: "recursive-call",
    },
    {
      line: 10,
      code: "grid = [",
      explanation: "定义包含一个五单元格连通区域的示例网格。",
      role: "state-update",
    },
    {
      line: 15,
      code: "visited = set()",
      explanation: "创建集合记录已访问的网格坐标。",
      role: "state-update",
    },
    {
      line: 16,
      code: "dfs(grid, 0, 0, visited)",
      explanation: "从左上角 (0, 0) 启动 DFS。",
      role: "recursive-call",
    },
    {
      line: 17,
      code: "print(len(visited))",
      explanation: "打印从起点可达的非零单元格数量。",
      role: "output",
    },
  ],
  traceSteps: [
    {
      step: 1,
      line: 16,
      event: "start",
      description: "从 grid 的 (0, 0) 启动 DFS。",
      variables: { row: 0, col: 0, visited: "" },
      changedVariables: ["row", "col", "visited"],
    },
    {
      step: 2,
      line: 6,
      event: "call",
      description: "访问 (0, 0) 并加入 visited。",
      variables: { row: 0, col: 0, visited: "(0,0)" },
      changedVariables: ["visited"],
    },
    {
      step: 3,
      line: 8,
      event: "call",
      description: "从 (0, 0) 向右访问 (0, 1)。",
      variables: { row: 0, col: 1, visited: "(0,0),(0,1)" },
      changedVariables: ["col", "visited"],
    },
    {
      step: 4,
      line: 8,
      event: "call",
      description: "从 (0, 1) 向下访问 (1, 1)。",
      variables: { row: 1, col: 1, visited: "(0,0),(0,1),(1,1)" },
      changedVariables: ["row", "visited"],
    },
    {
      step: 5,
      line: 8,
      event: "call",
      description: "继续访问 (1, 2)，再向下到达 (2, 2)。",
      variables: {
        row: 2,
        col: 2,
        visited: "(0,0),(0,1),(1,1),(1,2),(2,2)",
      },
      changedVariables: ["row", "col", "visited"],
    },
    {
      step: 6,
      line: 8,
      event: "return",
      description: "所有递归分支结束并回到顶层调用。",
      variables: { row: 0, col: 0, visited: "5 cells", visitedCount: 5 },
      changedVariables: ["visitedCount"],
    },
    {
      step: 7,
      line: 17,
      event: "output",
      description: "打印 visited 的大小 5。",
      variables: { row: 0, col: 0, visited: "5 cells", visitedCount: 5 },
      changedVariables: [],
      stdout: "5",
    },
  ],
  stackFrames: [],
  recommendations: [],
  warnings: [],
  source: "mock",
};

export const climbingStairsAnalysis: CodeAnalyzeResponse = {
  requestId: "mock-climbing-stairs-base",
  language: "python",
  title: "爬楼梯动态规划状态更新",
  summary:
    "climb(5) 用 previous 和 current 滚动保存相邻状态，每轮执行 previous, current = current, previous + current，5 轮后 previous 为 8。",
  detectedConcepts: ["动态规划", "滚动变量", "状态转移", "循环"],
  complexity: {
    time: "O(n)",
    space: "O(1)",
    explanation: "循环执行 n 次，每次只更新 previous 和 current 两个状态变量。",
  },
  lineExplanations: [
    {
      line: 1,
      code: "def climb(n):",
      explanation: "定义计算 n 阶楼梯走法数量的函数。",
      role: "input",
    },
    {
      line: 2,
      code: "    previous, current = 1, 1",
      explanation: "初始化两个相邻状态，分别表示当前和下一阶的走法数。",
      role: "state-update",
    },
    {
      line: 3,
      code: "    for _ in range(n):",
      explanation: "按楼梯阶数重复进行状态转移。",
      role: "loop",
    },
    {
      line: 4,
      code: "        previous, current = current, previous + current",
      explanation: "当前状态前移，并用前两个状态之和计算下一状态。",
      role: "state-update",
    },
    {
      line: 5,
      code: "    return previous",
      explanation: "循环结束后返回 n 阶楼梯的走法数量。",
      role: "return",
    },
    {
      line: 7,
      code: "print(climb(5))",
      explanation: "计算 5 阶楼梯并打印结果。",
      role: "output",
    },
  ],
  traceSteps: [
    {
      step: 1,
      line: 7,
      event: "start",
      description: "开始计算 climb(5)。",
      variables: { n: 5 },
      changedVariables: ["n"],
    },
    {
      step: 2,
      line: 2,
      event: "assign",
      description: "初始化 previous=1、current=1。",
      variables: { n: 5, previous: 1, current: 1 },
      changedVariables: ["previous", "current"],
    },
    {
      step: 3,
      line: 4,
      event: "loop",
      description: "第 1 轮后状态更新为 previous=1、current=2。",
      variables: { iteration: 1, previous: 1, current: 2 },
      changedVariables: ["iteration", "current"],
    },
    {
      step: 4,
      line: 4,
      event: "loop",
      description: "第 3 轮后状态更新为 previous=3、current=5。",
      variables: { iteration: 3, previous: 3, current: 5 },
      changedVariables: ["iteration", "previous", "current"],
    },
    {
      step: 5,
      line: 4,
      event: "loop",
      description: "第 5 轮后状态更新为 previous=8、current=13。",
      variables: { iteration: 5, previous: 8, current: 13 },
      changedVariables: ["iteration", "previous", "current"],
    },
    {
      step: 6,
      line: 5,
      event: "return",
      description: "返回 previous 的值 8。",
      variables: { previous: 8, current: 13, returnValue: 8 },
      changedVariables: ["returnValue"],
    },
  ],
  stackFrames: [],
  recommendations: [],
  warnings: [],
  source: "mock",
};

export const acceptanceBinarySearchAnalysis: CodeAnalyzeResponse = {
  ...binarySearchAnalysis,
  summary:
    "在 [1, 3, 5, 7, 9] 中查找目标值 7：先检查索引 2，再把 left 收缩到 3，最终返回索引 3。",
  traceSteps: [
    { step: 1, line: 13, event: "start", description: "开始在 5 个有序元素中查找 7。", variables: { target: 7, itemCount: 5 }, changedVariables: ["target", "itemCount"], activeFrameId: "frame-binary-search" },
    { step: 2, line: 2, event: "assign", description: "初始化 left=0、right=4。", variables: { left: 0, right: 4, target: 7 }, changedVariables: ["left", "right"], activeFrameId: "frame-binary-search" },
    { step: 3, line: 3, event: "loop", description: "0 <= 4，搜索区间有效。", variables: { left: 0, right: 4 }, changedVariables: [], activeFrameId: "frame-binary-search" },
    { step: 4, line: 4, event: "assign", description: "计算 mid=2，中点值为 5。", variables: { left: 0, right: 4, mid: 2, midValue: 5 }, changedVariables: ["mid", "midValue"], activeFrameId: "frame-binary-search" },
    { step: 5, line: 5, event: "condition", description: "5 不等于目标 7。", variables: { left: 0, right: 4, mid: 2, isMatch: false }, changedVariables: ["isMatch"], activeFrameId: "frame-binary-search" },
    { step: 6, line: 7, event: "condition", description: "5 < 7，保留右半区间。", variables: { left: 0, right: 4, mid: 2, searchRight: true }, changedVariables: ["searchRight"], activeFrameId: "frame-binary-search" },
    { step: 7, line: 8, event: "assign", description: "把 left 更新为 3。", variables: { left: 3, right: 4, mid: 2 }, changedVariables: ["left"], activeFrameId: "frame-binary-search" },
    { step: 8, line: 3, event: "loop", description: "3 <= 4，继续搜索。", variables: { left: 3, right: 4, mid: 2 }, changedVariables: [], activeFrameId: "frame-binary-search" },
    { step: 9, line: 4, event: "assign", description: "计算 mid=3，中点值为 7。", variables: { left: 3, right: 4, mid: 3, midValue: 7 }, changedVariables: ["mid", "midValue"], activeFrameId: "frame-binary-search" },
    { step: 10, line: 5, event: "condition", description: "中点值 7 等于目标值。", variables: { left: 3, right: 4, mid: 3, isMatch: true }, changedVariables: ["isMatch"], activeFrameId: "frame-binary-search" },
    { step: 11, line: 6, event: "return", description: "返回索引 3。", variables: { left: 3, right: 4, mid: 3, returnValue: 3 }, changedVariables: ["returnValue"], activeFrameId: "frame-binary-search" },
    { step: 12, line: 13, event: "output", description: "print 输出索引 3。", variables: { result: 3 }, changedVariables: ["result"], stdout: "3" },
    { step: 13, line: 13, event: "end", description: "程序执行结束。", variables: { result: 3 }, changedVariables: [], stdout: "3" },
  ],
  stackFrames: [
    { step: 1, frames: [{ id: "frame-binary-search", functionName: "binary_search", line: 1, params: { target: 7, itemCount: 5 }, locals: {}, status: "active" }] },
    { step: 4, frames: [{ id: "frame-binary-search", functionName: "binary_search", line: 4, params: { target: 7, itemCount: 5 }, locals: { left: 0, right: 4, mid: 2, midValue: 5 }, status: "active" }] },
    { step: 9, frames: [{ id: "frame-binary-search", functionName: "binary_search", line: 4, params: { target: 7, itemCount: 5 }, locals: { left: 3, right: 4, mid: 3, midValue: 7 }, status: "active" }] },
    { step: 11, frames: [{ id: "frame-binary-search", functionName: "binary_search", line: 6, params: { target: 7, itemCount: 5 }, locals: { left: 3, right: 4, mid: 3, midValue: 7 }, status: "returned", returnValue: 3 }] },
  ],
};

export const acceptanceBracketStackAnalysis: CodeAnalyzeResponse = {
  ...bracketStackAnalysis,
  lineExplanations: [
    { line: 1, code: "", explanation: "定义检查括号字符串是否合法的函数。", role: "input" },
    { line: 2, code: "", explanation: "创建栈保存尚未匹配的左括号。", role: "state-update" },
    { line: 3, code: "", explanation: "记录右括号到左括号的对应关系。", role: "state-update" },
    { line: 4, code: "", explanation: "逐个读取字符串中的括号。", role: "loop" },
    { line: 5, code: "", explanation: "左括号需要压入栈。", role: "condition" },
    { line: 6, code: "", explanation: "把当前左括号压入栈。", role: "state-update" },
    { line: 7, code: "", explanation: "右括号需要与栈顶配对。", role: "condition" },
    { line: 8, code: "", explanation: "栈为空或栈顶类型不匹配时失败。", role: "condition" },
    { line: 9, code: "", explanation: "发现不匹配时立即返回 False。", role: "return" },
    { line: 10, code: "", explanation: "匹配成功后弹出栈顶左括号。", role: "state-update" },
    { line: 11, code: "", explanation: "遍历结束时空栈表示全部匹配。", role: "return" },
    { line: 13, code: "", explanation: "检查 '([])' 并打印结果。", role: "output" },
  ],
  traceSteps: [
    { step: 1, line: 13, event: "start", description: "开始检查文本 '([])'。", variables: { s: "([])" }, changedVariables: ["s"], activeFrameId: "frame-is-valid" },
    { step: 2, line: 2, event: "assign", description: "初始化空栈。", variables: { ch: "", stack: "" }, changedVariables: ["stack"], activeFrameId: "frame-is-valid" },
    { step: 3, line: 6, event: "push", description: "读取 '(' 并压栈。", variables: { ch: "(", stack: "(" }, changedVariables: ["ch", "stack"], activeFrameId: "frame-is-valid" },
    { step: 4, line: 6, event: "push", description: "读取 '[' 并压栈。", variables: { ch: "[", stack: "([" }, changedVariables: ["ch", "stack"], activeFrameId: "frame-is-valid" },
    { step: 5, line: 8, event: "condition", description: "']' 与栈顶 '[' 匹配。", variables: { ch: "]", stack: "([", matched: true }, changedVariables: ["ch", "matched"], activeFrameId: "frame-is-valid" },
    { step: 6, line: 10, event: "pop", description: "弹出 '['。", variables: { ch: "]", popped: "[", stack: "(" }, changedVariables: ["popped", "stack"], activeFrameId: "frame-is-valid" },
    { step: 7, line: 8, event: "condition", description: "')' 与栈顶 '(' 匹配。", variables: { ch: ")", stack: "(", matched: true }, changedVariables: ["ch"], activeFrameId: "frame-is-valid" },
    { step: 8, line: 10, event: "pop", description: "弹出 '('。", variables: { ch: ")", popped: "(", stack: "" }, changedVariables: ["popped", "stack"], activeFrameId: "frame-is-valid" },
    { step: 9, line: 11, event: "return", description: "栈为空，返回 True。", variables: { stack: "", returnValue: true }, changedVariables: ["returnValue"], activeFrameId: "frame-is-valid" },
    { step: 10, line: 13, event: "output", description: "print 输出 True。", variables: { result: true }, changedVariables: ["result"], stdout: "True" },
    { step: 11, line: 13, event: "end", description: "程序执行结束。", variables: { result: true }, changedVariables: [], stdout: "True" },
  ],
  stackFrames: [
    { step: 1, frames: [{ id: "frame-is-valid", functionName: "is_valid", line: 1, params: { s: "([])" }, locals: { stack: "" }, status: "active" }] },
    { step: 9, frames: [{ id: "frame-is-valid", functionName: "is_valid", line: 11, params: { s: "([])" }, locals: { stack: "" }, status: "returned", returnValue: true }] },
  ],
};

const DFS_VISITED = "(0,0),(0,1),(1,1),(1,2),(2,2)";

export const acceptanceDepthFirstSearchAnalysis: CodeAnalyzeResponse = {
  ...depthFirstSearchAnalysis,
  traceSteps: depthFirstSearchAnalysis.traceSteps.map((step) => {
    const activeFrameIds: Record<number, string> = {
      1: "frame-dfs-0-0",
      2: "frame-dfs-0-0",
      3: "frame-dfs-0-1",
      4: "frame-dfs-1-1",
      5: "frame-dfs-2-2",
      6: "frame-dfs-0-0",
    };
    if (step.step === 6) {
      return { ...step, variables: { row: 0, col: 0, visited: DFS_VISITED, visitedCount: 5 }, changedVariables: ["visitedCount"], activeFrameId: activeFrameIds[step.step] };
    }
    return { ...step, activeFrameId: activeFrameIds[step.step] };
  }),
  stackFrames: [
    { step: 1, frames: [{ id: "frame-dfs-0-0", functionName: "dfs", line: 1, params: { row: 0, col: 0 }, locals: { visited: "" }, status: "active" }] },
    { step: 2, frames: [{ id: "frame-dfs-0-0", functionName: "dfs", line: 6, params: { row: 0, col: 0 }, locals: { visited: "(0,0)" }, status: "active" }] },
    { step: 3, frames: [
      { id: "frame-dfs-0-0", functionName: "dfs", line: 8, params: { row: 0, col: 0 }, locals: { visited: "(0,0),(0,1)" }, status: "waiting" },
      { id: "frame-dfs-0-1", functionName: "dfs", line: 6, params: { row: 0, col: 1 }, locals: { visited: "(0,0),(0,1)" }, status: "active" },
    ] },
    { step: 4, frames: [
      { id: "frame-dfs-0-0", functionName: "dfs", line: 8, params: { row: 0, col: 0 }, locals: { visited: "(0,0),(0,1),(1,1)" }, status: "waiting" },
      { id: "frame-dfs-0-1", functionName: "dfs", line: 8, params: { row: 0, col: 1 }, locals: { visited: "(0,0),(0,1),(1,1)" }, status: "waiting" },
      { id: "frame-dfs-1-1", functionName: "dfs", line: 6, params: { row: 1, col: 1 }, locals: { visited: "(0,0),(0,1),(1,1)" }, status: "active" },
    ] },
    { step: 5, frames: [
      { id: "frame-dfs-0-0", functionName: "dfs", line: 8, params: { row: 0, col: 0 }, locals: { visited: DFS_VISITED }, status: "waiting" },
      { id: "frame-dfs-0-1", functionName: "dfs", line: 8, params: { row: 0, col: 1 }, locals: { visited: DFS_VISITED }, status: "waiting" },
      { id: "frame-dfs-1-1", functionName: "dfs", line: 8, params: { row: 1, col: 1 }, locals: { visited: DFS_VISITED }, status: "waiting" },
      { id: "frame-dfs-1-2", functionName: "dfs", line: 8, params: { row: 1, col: 2 }, locals: { visited: DFS_VISITED }, status: "waiting" },
      { id: "frame-dfs-2-2", functionName: "dfs", line: 6, params: { row: 2, col: 2 }, locals: { visited: DFS_VISITED }, status: "active" },
    ] },
    { step: 6, frames: [{ id: "frame-dfs-0-0", functionName: "dfs", line: 8, params: { row: 0, col: 0 }, locals: { visited: DFS_VISITED }, status: "returned" }] },
  ],
};

export const acceptanceClimbingStairsAnalysis: CodeAnalyzeResponse = {
  ...climbingStairsAnalysis,
  traceSteps: [
    { step: 1, line: 7, event: "start", description: "开始计算 climb(5)。", variables: { n: 5 }, changedVariables: ["n"] },
    { step: 2, line: 2, event: "assign", description: "初始化 previous=1、current=1。", variables: { n: 5, previous: 1, current: 1 }, changedVariables: ["previous", "current"] },
    { step: 3, line: 4, event: "loop", description: "第 1 轮：previous=1、current=2。", variables: { iteration: 1, previous: 1, current: 2 }, changedVariables: ["iteration", "current"] },
    { step: 4, line: 4, event: "loop", description: "第 2 轮：previous=2、current=3。", variables: { iteration: 2, previous: 2, current: 3 }, changedVariables: ["iteration", "previous", "current"] },
    { step: 5, line: 4, event: "loop", description: "第 3 轮：previous=3、current=5。", variables: { iteration: 3, previous: 3, current: 5 }, changedVariables: ["iteration", "previous", "current"] },
    { step: 6, line: 4, event: "loop", description: "第 4 轮：previous=5、current=8。", variables: { iteration: 4, previous: 5, current: 8 }, changedVariables: ["iteration", "previous", "current"] },
    { step: 7, line: 4, event: "loop", description: "第 5 轮：previous=8、current=13。", variables: { iteration: 5, previous: 8, current: 13 }, changedVariables: ["iteration", "previous", "current"] },
    { step: 8, line: 5, event: "return", description: "返回 previous 的值 8。", variables: { previous: 8, current: 13, returnValue: 8 }, changedVariables: ["returnValue"] },
    { step: 9, line: 7, event: "output", description: "print 输出 8。", variables: { result: 8 }, changedVariables: ["result"], stdout: "8" },
    { step: 10, line: 7, event: "end", description: "程序执行结束。", variables: { result: 8 }, changedVariables: [], stdout: "8" },
  ],
};
