import type { CodeAnalyzeResponse } from "./types.js";

export const fibonacciCode = `def fib(n):
    if n <= 1:
        return n
    return fib(n - 1) + fib(n - 2)

print(fib(4))`;

const binarySearchCode = `def binary_search(items, target):
    left, right = 0, len(items) - 1
    while left <= right:
        mid = (left + right) // 2
        if items[mid] == target:
            return mid
        if items[mid] < target:
            left = mid + 1
        else:
            right = mid - 1
    return -1

print(binary_search([1, 3, 5, 7, 9], 7))`;

export const examples = [
  {
    id: "fibonacci-recursion",
    title: "斐波那契递归",
    concept: "递归与 base case",
    code: fibonacciCode,
  },
  {
    id: "binary-search",
    title: "二分查找",
    concept: "区间收缩与中点",
    code: binarySearchCode,
  },
  {
    id: "bracket-stack",
    title: "括号匹配",
    concept: "栈的压入与弹出",
    code: `def is_valid(text):
    stack = []
    pairs = {')': '(', ']': '[', '}': '{'}
    for char in text:
        if char in '([{':
            stack.append(char)
        elif not stack or stack.pop() != pairs[char]:
            return False
    return not stack

print(is_valid('([])'))`,
  },
  {
    id: "running-total",
    title: "循环求和",
    concept: "循环与状态更新",
    code: `total = 0
for number in range(1, 6):
    total += number
print(total)`,
  },
  {
    id: "climbing-stairs",
    title: "爬楼梯",
    concept: "动态规划",
    code: `def climb(n):
    previous, current = 1, 1
    for _ in range(n):
        previous, current = current, previous + current
    return previous

print(climb(5))`,
  },
] as const;

export const fibonacciAnalysis: CodeAnalyzeResponse = {
  requestId: "mock-fibonacci-base",
  language: "python",
  title: "斐波那契递归执行过程",
  summary:
    "fib(4) 会拆分成更小的 fib 调用，直到 fib(1) 或 fib(0) 命中递归出口，再逐层合并返回值。",
  detectedConcepts: ["递归", "base case", "调用栈", "分治"],
  complexity: {
    time: "O(2^n)",
    space: "O(n)",
    explanation:
      "朴素递归会重复计算相同子问题；最大递归深度与 n 成正比。",
  },
  lineExplanations: [
    {
      line: 1,
      code: "def fib(n):",
      explanation: "定义接收整数 n 的斐波那契函数。",
      role: "input",
    },
    {
      line: 2,
      code: "if n <= 1:",
      explanation: "判断是否到达 fib(0) 或 fib(1) 的递归出口。",
      role: "condition",
    },
    {
      line: 3,
      code: "return n",
      explanation: "出口直接返回 0 或 1，停止继续向下递归。",
      role: "return",
    },
    {
      line: 4,
      code: "return fib(n - 1) + fib(n - 2)",
      explanation: "分别计算两个更小的子问题，并将返回值相加。",
      role: "recursive-call",
    },
    {
      line: 6,
      code: "print(fib(4))",
      explanation: "从 fib(4) 开始执行，并输出最终结果 3。",
      role: "output",
    },
  ],
  traceSteps: [
    {
      step: 1,
      line: 6,
      event: "start",
      description: "程序准备计算 fib(4)。",
      variables: { n: 4 },
      changedVariables: ["n"],
    },
    {
      step: 2,
      line: 1,
      event: "call",
      description: "进入 fib(4)，创建根调用帧。",
      variables: { n: 4 },
      changedVariables: ["n"],
      activeFrameId: "frame-f4",
      activeRecursionNodeId: "fib-4",
    },
    {
      step: 3,
      line: 2,
      event: "condition",
      description: "4 <= 1 为 False，需要继续递归。",
      variables: { n: 4, isBaseCase: false },
      changedVariables: ["isBaseCase"],
      activeFrameId: "frame-f4",
      activeRecursionNodeId: "fib-4",
    },
    {
      step: 4,
      line: 4,
      event: "call",
      description: "fib(4) 首先调用 fib(3)。",
      variables: { n: 3 },
      changedVariables: ["n"],
      activeFrameId: "frame-f3",
      activeRecursionNodeId: "fib-3",
    },
    {
      step: 5,
      line: 4,
      event: "call",
      description: "fib(3) 首先调用 fib(2)。",
      variables: { n: 2 },
      changedVariables: ["n"],
      activeFrameId: "frame-f2-left",
      activeRecursionNodeId: "fib-2-left",
    },
    {
      step: 6,
      line: 4,
      event: "call",
      description: "fib(2) 调用 fib(1)。",
      variables: { n: 1 },
      changedVariables: ["n"],
      activeFrameId: "frame-f1-left",
      activeRecursionNodeId: "fib-1-left",
    },
    {
      step: 7,
      line: 3,
      event: "return",
      description: "fib(1) 命中 base case，返回 1。",
      variables: { n: 1, returnValue: 1 },
      changedVariables: ["returnValue"],
      activeFrameId: "frame-f1-left",
      activeRecursionNodeId: "fib-1-left",
    },
    {
      step: 8,
      line: 4,
      event: "call",
      description: "fib(2) 继续调用 fib(0)。",
      variables: { n: 0 },
      changedVariables: ["n"],
      activeFrameId: "frame-f0-left",
      activeRecursionNodeId: "fib-0-left",
    },
    {
      step: 9,
      line: 3,
      event: "return",
      description: "fib(0) 命中 base case，返回 0。",
      variables: { n: 0, returnValue: 0 },
      changedVariables: ["returnValue"],
      activeFrameId: "frame-f0-left",
      activeRecursionNodeId: "fib-0-left",
    },
    {
      step: 10,
      line: 4,
      event: "return",
      description: "fib(2) 合并 1 + 0，返回 1。",
      variables: { n: 2, leftValue: 1, rightValue: 0, returnValue: 1 },
      changedVariables: ["returnValue"],
      activeFrameId: "frame-f2-left",
      activeRecursionNodeId: "fib-2-left",
    },
    {
      step: 11,
      line: 4,
      event: "call",
      description: "fib(3) 再调用 fib(1)。",
      variables: { n: 1 },
      changedVariables: ["n"],
      activeFrameId: "frame-f1-middle",
      activeRecursionNodeId: "fib-1-middle",
    },
    {
      step: 12,
      line: 3,
      event: "return",
      description: "第二个 fib(1) 返回 1。",
      variables: { n: 1, returnValue: 1 },
      changedVariables: ["returnValue"],
      activeFrameId: "frame-f1-middle",
      activeRecursionNodeId: "fib-1-middle",
    },
    {
      step: 13,
      line: 4,
      event: "return",
      description: "fib(3) 合并 1 + 1，返回 2。",
      variables: { n: 3, leftValue: 1, rightValue: 1, returnValue: 2 },
      changedVariables: ["returnValue"],
      activeFrameId: "frame-f3",
      activeRecursionNodeId: "fib-3",
    },
    {
      step: 14,
      line: 4,
      event: "call",
      description: "fib(4) 开始计算右侧的 fib(2)。",
      variables: { n: 2 },
      changedVariables: ["n"],
      activeFrameId: "frame-f2-right",
      activeRecursionNodeId: "fib-2-right",
    },
    {
      step: 15,
      line: 4,
      event: "call",
      description: "右侧 fib(2) 调用 fib(1)。",
      variables: { n: 1 },
      changedVariables: ["n"],
      activeFrameId: "frame-f1-right",
      activeRecursionNodeId: "fib-1-right",
    },
    {
      step: 16,
      line: 3,
      event: "return",
      description: "右侧 fib(1) 返回 1。",
      variables: { n: 1, returnValue: 1 },
      changedVariables: ["returnValue"],
      activeFrameId: "frame-f1-right",
      activeRecursionNodeId: "fib-1-right",
    },
    {
      step: 17,
      line: 4,
      event: "call",
      description: "右侧 fib(2) 调用 fib(0)。",
      variables: { n: 0 },
      changedVariables: ["n"],
      activeFrameId: "frame-f0-right",
      activeRecursionNodeId: "fib-0-right",
    },
    {
      step: 18,
      line: 3,
      event: "return",
      description: "右侧 fib(0) 返回 0。",
      variables: { n: 0, returnValue: 0 },
      changedVariables: ["returnValue"],
      activeFrameId: "frame-f0-right",
      activeRecursionNodeId: "fib-0-right",
    },
    {
      step: 19,
      line: 4,
      event: "return",
      description: "右侧 fib(2) 合并 1 + 0，返回 1。",
      variables: { n: 2, leftValue: 1, rightValue: 0, returnValue: 1 },
      changedVariables: ["returnValue"],
      activeFrameId: "frame-f2-right",
      activeRecursionNodeId: "fib-2-right",
    },
    {
      step: 20,
      line: 4,
      event: "return",
      description: "fib(4) 合并 2 + 1，返回 3。",
      variables: { n: 4, leftValue: 2, rightValue: 1, returnValue: 3 },
      changedVariables: ["returnValue"],
      activeFrameId: "frame-f4",
      activeRecursionNodeId: "fib-4",
    },
    {
      step: 21,
      line: 6,
      event: "output",
      description: "print 输出 fib(4) 的结果 3。",
      variables: { result: 3 },
      changedVariables: ["result"],
      stdout: "3",
    },
    {
      step: 22,
      line: 6,
      event: "end",
      description: "程序执行结束。",
      variables: { result: 3 },
      changedVariables: [],
      stdout: "3",
    },
  ],
  stackFrames: [
    {
      step: 2,
      frames: [
        {
          id: "frame-f4",
          functionName: "fib",
          line: 1,
          params: { n: 4 },
          locals: {},
          status: "active",
        },
      ],
    },
    {
      step: 5,
      frames: [
        {
          id: "frame-f4",
          functionName: "fib",
          line: 4,
          params: { n: 4 },
          locals: {},
          status: "waiting",
        },
        {
          id: "frame-f3",
          functionName: "fib",
          line: 4,
          params: { n: 3 },
          locals: {},
          status: "waiting",
        },
        {
          id: "frame-f2-left",
          functionName: "fib",
          line: 1,
          params: { n: 2 },
          locals: {},
          status: "active",
        },
      ],
    },
    {
      step: 7,
      frames: [
        {
          id: "frame-f4",
          functionName: "fib",
          line: 4,
          params: { n: 4 },
          locals: {},
          status: "waiting",
        },
        {
          id: "frame-f3",
          functionName: "fib",
          line: 4,
          params: { n: 3 },
          locals: {},
          status: "waiting",
        },
        {
          id: "frame-f2-left",
          functionName: "fib",
          line: 4,
          params: { n: 2 },
          locals: { leftValue: 1 },
          status: "active",
        },
        {
          id: "frame-f1-left",
          functionName: "fib",
          line: 3,
          params: { n: 1 },
          locals: {},
          status: "returned",
          returnValue: 1,
        },
      ],
    },
    {
      step: 13,
      frames: [
        {
          id: "frame-f4",
          functionName: "fib",
          line: 4,
          params: { n: 4 },
          locals: { leftValue: 2 },
          status: "active",
        },
        {
          id: "frame-f3",
          functionName: "fib",
          line: 4,
          params: { n: 3 },
          locals: { leftValue: 1, rightValue: 1 },
          status: "returned",
          returnValue: 2,
        },
      ],
    },
    {
      step: 20,
      frames: [
        {
          id: "frame-f4",
          functionName: "fib",
          line: 4,
          params: { n: 4 },
          locals: { leftValue: 2, rightValue: 1 },
          status: "returned",
          returnValue: 3,
        },
      ],
    },
  ],
  recursionTree: {
    rootId: "fib-4",
    nodes: [
      {
        id: "fib-4",
        label: "fib(4)",
        functionName: "fib",
        args: { n: 4 },
        status: "returned",
        returnValue: 3,
        enterStep: 2,
        exitStep: 20,
      },
      {
        id: "fib-3",
        label: "fib(3)",
        functionName: "fib",
        args: { n: 3 },
        status: "returned",
        returnValue: 2,
        enterStep: 4,
        exitStep: 13,
      },
      {
        id: "fib-2-left",
        label: "fib(2)",
        functionName: "fib",
        args: { n: 2 },
        status: "returned",
        returnValue: 1,
        enterStep: 5,
        exitStep: 10,
      },
      {
        id: "fib-1-left",
        label: "fib(1)",
        functionName: "fib",
        args: { n: 1 },
        status: "returned",
        returnValue: 1,
        enterStep: 6,
        exitStep: 7,
      },
      {
        id: "fib-0-left",
        label: "fib(0)",
        functionName: "fib",
        args: { n: 0 },
        status: "returned",
        returnValue: 0,
        enterStep: 8,
        exitStep: 9,
      },
      {
        id: "fib-1-middle",
        label: "fib(1)",
        functionName: "fib",
        args: { n: 1 },
        status: "returned",
        returnValue: 1,
        enterStep: 11,
        exitStep: 12,
      },
      {
        id: "fib-2-right",
        label: "fib(2)",
        functionName: "fib",
        args: { n: 2 },
        status: "returned",
        returnValue: 1,
        enterStep: 14,
        exitStep: 19,
      },
      {
        id: "fib-1-right",
        label: "fib(1)",
        functionName: "fib",
        args: { n: 1 },
        status: "returned",
        returnValue: 1,
        enterStep: 15,
        exitStep: 16,
      },
      {
        id: "fib-0-right",
        label: "fib(0)",
        functionName: "fib",
        args: { n: 0 },
        status: "returned",
        returnValue: 0,
        enterStep: 17,
        exitStep: 18,
      },
    ],
    edges: [
      { from: "fib-4", to: "fib-3", label: "n - 1" },
      { from: "fib-4", to: "fib-2-right", label: "n - 2" },
      { from: "fib-3", to: "fib-2-left", label: "n - 1" },
      { from: "fib-3", to: "fib-1-middle", label: "n - 2" },
      { from: "fib-2-left", to: "fib-1-left", label: "n - 1" },
      { from: "fib-2-left", to: "fib-0-left", label: "n - 2" },
      { from: "fib-2-right", to: "fib-1-right", label: "n - 1" },
      { from: "fib-2-right", to: "fib-0-right", label: "n - 2" },
    ],
  },
  recommendations: [
    {
      id: "memoized-fibonacci",
      title: "给斐波那契递归添加缓存",
      difficulty: "beginner",
      concepts: ["递归", "记忆化"],
      reason: "观察并消除 fib(2) 等子问题的重复计算。",
      visualizationHint: "对比加入缓存前后的递归树节点数量。",
      starterPrompt: "使用字典保存已经计算过的 fib(n)。",
    },
    {
      id: "factorial-recursion",
      title: "跟踪阶乘递归",
      difficulty: "beginner",
      concepts: ["递归出口", "调用栈"],
      reason: "用单分支递归巩固进入与回退过程。",
      visualizationHint: "逐步查看每一层参数和返回值。",
    },
    {
      id: "iterative-fibonacci",
      title: "改写为循环版本",
      difficulty: "intermediate",
      concepts: ["循环", "状态更新", "空间优化"],
      reason: "理解相同问题如何用常量额外空间求解。",
      visualizationHint: "跟踪 previous 和 current 的每次变化。",
    },
  ],
  warnings: [
    {
      code: "MOCK_USED",
      message: "当前展示稳定的斐波那契 mock 分析结果。",
    },
  ],
  source: "mock",
};

export const binarySearchAnalysis: CodeAnalyzeResponse = {
  requestId: "mock-binary-search-base",
  language: "python",
  title: "二分查找区间变化",
  summary:
    "算法通过比较中点元素与目标值，不断收缩 left 和 right，最终在索引 3 找到目标 7。",
  detectedConcepts: ["二分查找", "循环", "区间边界", "整数除法"],
  complexity: {
    time: "O(log n)",
    space: "O(1)",
    explanation: "每次比较都会排除约一半搜索区间，并且只使用固定数量变量。",
  },
  lineExplanations: [
    {
      line: 1,
      code: "def binary_search(items, target):",
      explanation: "定义在有序序列中查找 target 的函数。",
      role: "input",
    },
    {
      line: 2,
      code: "left, right = 0, len(items) - 1",
      explanation: "将搜索区间初始化为整个序列。",
      role: "state-update",
    },
    {
      line: 3,
      code: "while left <= right:",
      explanation: "只要区间仍然有效，就继续查找。",
      role: "loop",
    },
    {
      line: 4,
      code: "mid = (left + right) // 2",
      explanation: "计算当前区间的中点索引。",
      role: "state-update",
    },
    {
      line: 5,
      code: "if items[mid] == target:",
      explanation: "检查中点元素是否就是目标值。",
      role: "condition",
    },
    {
      line: 6,
      code: "return mid",
      explanation: "找到目标后返回中点索引。",
      role: "return",
    },
    {
      line: 7,
      code: "if items[mid] < target:",
      explanation: "目标更大时，排除中点及其左侧区间。",
      role: "condition",
    },
    {
      line: 8,
      code: "left = mid + 1",
      explanation: "把左边界移动到中点右侧。",
      role: "state-update",
    },
    {
      line: 9,
      code: "else:",
      explanation: "否则目标位于中点左侧。",
      role: "condition",
    },
    {
      line: 10,
      code: "right = mid - 1",
      explanation: "把右边界移动到中点左侧。",
      role: "state-update",
    },
    {
      line: 11,
      code: "return -1",
      explanation: "区间耗尽仍未找到时返回 -1。",
      role: "return",
    },
    {
      line: 13,
      code: "print(binary_search([1, 3, 5, 7, 9], 7))",
      explanation: "查找目标 7，并输出索引 3。",
      role: "output",
    },
  ],
  traceSteps: [
    {
      step: 1,
      line: 1,
      event: "start",
      description: "开始在 5 个有序元素中查找 7。",
      variables: { target: 7, itemCount: 5 },
      changedVariables: ["target", "itemCount"],
      activeFrameId: "frame-binary-search",
    },
    {
      step: 2,
      line: 2,
      event: "assign",
      description: "初始化搜索边界 left=0、right=4。",
      variables: { left: 0, right: 4, target: 7 },
      changedVariables: ["left", "right"],
      activeFrameId: "frame-binary-search",
    },
    {
      step: 3,
      line: 3,
      event: "loop",
      description: "0 <= 4，搜索区间有效。",
      variables: { left: 0, right: 4 },
      changedVariables: [],
      activeFrameId: "frame-binary-search",
    },
    {
      step: 4,
      line: 4,
      event: "assign",
      description: "计算中点 mid=2，中点元素为 5。",
      variables: { left: 0, right: 4, mid: 2, midValue: 5 },
      changedVariables: ["mid", "midValue"],
      activeFrameId: "frame-binary-search",
    },
    {
      step: 5,
      line: 5,
      event: "condition",
      description: "中点元素 5 不等于目标 7。",
      variables: { left: 0, right: 4, mid: 2, isMatch: false },
      changedVariables: ["isMatch"],
      activeFrameId: "frame-binary-search",
    },
    {
      step: 6,
      line: 7,
      event: "condition",
      description: "5 < 7，目标位于右半区间。",
      variables: { left: 0, right: 4, mid: 2, searchRight: true },
      changedVariables: ["searchRight"],
      activeFrameId: "frame-binary-search",
    },
    {
      step: 7,
      line: 8,
      event: "assign",
      description: "将 left 更新为 3。",
      variables: { left: 3, right: 4, mid: 2 },
      changedVariables: ["left"],
      activeFrameId: "frame-binary-search",
    },
    {
      step: 8,
      line: 3,
      event: "loop",
      description: "3 <= 4，继续搜索。",
      variables: { left: 3, right: 4, mid: 2 },
      changedVariables: [],
      activeFrameId: "frame-binary-search",
    },
    {
      step: 9,
      line: 4,
      event: "assign",
      description: "重新计算 mid=3，中点元素为 7。",
      variables: { left: 3, right: 4, mid: 3, midValue: 7 },
      changedVariables: ["mid", "midValue"],
      activeFrameId: "frame-binary-search",
    },
    {
      step: 10,
      line: 5,
      event: "condition",
      description: "中点元素 7 等于目标值。",
      variables: { left: 3, right: 4, mid: 3, isMatch: true },
      changedVariables: ["isMatch"],
      activeFrameId: "frame-binary-search",
    },
    {
      step: 11,
      line: 6,
      event: "return",
      description: "返回找到的索引 3。",
      variables: { left: 3, right: 4, mid: 3, returnValue: 3 },
      changedVariables: ["returnValue"],
      activeFrameId: "frame-binary-search",
    },
    {
      step: 12,
      line: 13,
      event: "output",
      description: "print 输出索引 3。",
      variables: { result: 3 },
      changedVariables: ["result"],
      stdout: "3",
    },
    {
      step: 13,
      line: 13,
      event: "end",
      description: "程序执行结束，标准输出为 3。",
      variables: { result: 3 },
      changedVariables: [],
      stdout: "3",
    },
  ],
  stackFrames: [
    {
      step: 1,
      frames: [
        {
          id: "frame-binary-search",
          functionName: "binary_search",
          line: 1,
          params: { target: 7, itemCount: 5 },
          locals: {},
          status: "active",
        },
      ],
    },
    {
      step: 4,
      frames: [
        {
          id: "frame-binary-search",
          functionName: "binary_search",
          line: 4,
          params: { target: 7, itemCount: 5 },
          locals: { left: 0, right: 4, mid: 2, midValue: 5 },
          status: "active",
        },
      ],
    },
    {
      step: 7,
      frames: [
        {
          id: "frame-binary-search",
          functionName: "binary_search",
          line: 8,
          params: { target: 7, itemCount: 5 },
          locals: { left: 3, right: 4, mid: 2 },
          status: "active",
        },
      ],
    },
    {
      step: 11,
      frames: [
        {
          id: "frame-binary-search",
          functionName: "binary_search",
          line: 6,
          params: { target: 7, itemCount: 5 },
          locals: { left: 3, right: 4, mid: 3, midValue: 7 },
          status: "returned",
          returnValue: 3,
        },
      ],
    },
  ],
  recommendations: [
    {
      id: "binary-search-missing-target",
      title: "查找不存在的目标值",
      difficulty: "beginner",
      concepts: ["边界", "循环终止"],
      reason: "练习观察 left 超过 right 时算法如何结束。",
      visualizationHint: "跟踪每轮 left、right 和 mid。",
    },
    {
      id: "binary-search-first-position",
      title: "查找重复值的第一个位置",
      difficulty: "intermediate",
      concepts: ["二分查找", "边界收缩"],
      reason: "理解找到目标后继续向左收缩的变体。",
      visualizationHint: "标记候选答案和右边界的变化。",
    },
    {
      id: "guess-number",
      title: "猜数字区间策略",
      difficulty: "beginner",
      concepts: ["二分思想", "条件分支"],
      reason: "把二分查找迁移到直观的区间问题。",
      visualizationHint: "每轮高亮保留和排除的区间。",
    },
  ],
  warnings: [
    {
      code: "MOCK_USED",
      message: "当前展示稳定的二分查找 mock 分析结果。",
    },
  ],
  source: "mock",
};
